---
version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:8.3.3
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
    volumes:
      - .:/app
