# This is a basic workflow to help you get started with Actions
name: publicacion-db-pr

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  etl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn -B clean compile

      - name: Run extraction
        run: mvn -B exec:java -D"exec.mainClass"="op.congreso.pleno.app.CargaPlenos"

      - uses: actions/setup-python@v1
      - name: publishes to datasette
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            datasette
            sqlite-utils

      - name: Install vercel plugin
        run: |
          datasette install datasette-publish-vercel
          sqlite-utils enable-fts *.db votacion_resultado asunto etiquetas
          sqlite-utils enable-fts *.db votacion_grupo_parlamentario asunto etiquetas
          sqlite-utils enable-fts *.db votacion_congresista asunto etiquetas
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)
      - name: Deploy Datasette using Vercel
        id: deploy-datasette
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel *.db \
            --token $VERCEL_TOKEN \
            --no-prod \
            --project congreso-pleno-asistencia-votacion \
            --install datasette-vega \
            --install datasette-export-notebook \
            --install datasette-copyable \
            --install datasette-block-robots \
            --install datasette-pretty-json
