# This is a basic workflow to help you get started with Actions
name: publicacion-db

# Controls when the action will run.
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  etl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: echo
        run: |
          echo ${{steps.set.outputs.today}}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn -B clean compile

      - name: Run Actualizar Plenos
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn exec:java -D"exec.mainClass"="op.congreso.pleno.app.LoadRegitroPlenoDocuments"
      - name: Run Preparar Plenos DB
        run: mvn -B exec:java -D"exec.mainClass"="op.congreso.pleno.app.LoadDetallePlenosAndSave"

      - uses: actions/setup-python@v1
      - name: publishes to datasette
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            datasette
            sqlite-utils
            csvs-to-sqlite

      - name: Install vercel plugin
        run: |
          datasette install datasette-publish-vercel

      # Disabling to reduce the size of the image
      #- name: Prepare FTS
      #  run: |
      #    sqlite-utils enable-fts *.db votacion_resultado asunto etiquetas
      #    sqlite-utils enable-fts *.db votacion_grupo_parlamentario asunto etiquetas
      #    sqlite-utils enable-fts *.db votacion_congresista asunto etiquetas

      - name: Prepare Plenos DB
        run: |
          csvs-to-sqlite plenos.csv plenos.db

      - name: Deploy Datasette using Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel *.db \
            --token $VERCEL_TOKEN \
            --project congreso-pleno-asistencia-votacion \
            --install datasette-vega \
            --install datasette-export-notebook \
            --install datasette-copyable \
            --install datasette-block-robots \
            --install datasette-pretty-json \

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Cambios en Registro de Plenos
      #- name: Set
      #  id: set-pr
      #  run: |
      #    echo "::set-output name=pr-title::$(cat pr-title.txt)"
      #    echo "::set-output name=pr-content::$(cat pr-content.txt)"
      #    echo "::set-output name=pr-branch::$(cat pr-branch.txt)"
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v3
      #  with:
      #    title: ${{steps.set-pr.outputs.pr-title}}
      #    branch: ${{steps.set-pr.outputs.pr-branch}}
      #    body: ${{steps.set-pr.outputs.pr-content}}


