# This is a basic workflow to help you get started with Actions
name: carga-plenos

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  etl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn clean compile

      - name: Run extraction
        run: mvn exec:java -D"exec.mainClass"="op.congreso.pleno.CargarPlenos"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: main
          message: 'workflow: datos actualizados'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-python@v1
      - name: publishes to datasette
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            datasette
            sqlite-utils
            csvs-to-sqlite

      - name: Install vercel plugin
        run: |
          csvs-to-sqlite plenos.csv plenos.db
      - name: Install vercel plugin
        run: |
          datasette install datasette-publish-vercel
      - name: Deploy Datasette using Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel plenos.db \
            --token $VERCEL_TOKEN \
            --no-prod \
            --project congreso-pleno \
            --install datasette-vega \
            --install datasette-export-notebook \
            --install datasette-copyable \
            --install datasette-block-robots
